### ISSUE TITLE
Build Problems

### ISSUE THREAD

**Issue by Cris9807** [CMDRSpirit/RollercoasterDesigner#3] opened 2023-07-17 15:28 UTC
Hey,

When I want to build the scene it gives me the error The Name 'Undo' does not exist in the current context.

If I put the Undo lines in CoaserTrack..cs in IF sections the train won't move when playing the game in build mode.

**Comment by CMDRSpirit** [comment] 2023-07-18 17:40
Hey, thanks for reaching out. I've never tested it in standalone mode, of course the `Undo` calls have to be surrounded by 
`#if UNITY_EDITOR ... #endif` to successfully compile. Somehow, I completely fogot that.

There is also some code in the NURBS package that doesn't compile, which I will fix with the next commit.

I've replicated your issue and found the following problem:
When looking at the player log, the train and train audio manager have a `NullReference` somewhere (train: in `UpdatePhysics`, train audio: in the `Update` function).
I haven't found the variable that is causing the exception, but my best guess is that `OnValidate` overwrites the variable when building / opening the scene in standalone mode.

Maybe this helps tracking down the root cause.

**Comment by CMDRSpirit** [comment] 2023-07-23 10:42
Should be fixed now :) The problem was that for standalone builds, the track initialization wasn't running and therefore no information was present when trying to read the spline transforms.

**Closed by CMDRSpirit** 2023-07-23 10:42 UTC
